name: damage_proxy_maps
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pyproj  # Always include to avoid PROJ conflicts
  - jupyter
  - fiona
  - geopandas
  - sepal-ui>=2.22.2,<3
  - rasterio<=1.4.3
  - pip
  - gdal=3.10
  - pip:
    - opensartoolkit
    - git+https://github.com/openforis/earthengine-api.git@v1.1.5rc0#egg=earthengine-api&subdirectory=python
